site_name: My Cloud
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  # logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.select
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - About:
      - Overview: about/index.md
      - Experiences: about/experiences.md
      - Education: about/education.md
      - Skills: about/skills.md
      - Achievements: about/achievements.md
  - Projects:
      - Overview: projects/index.md
      - Atlantis: projects/atlantis.md
      - AnimeSage: projects/animesage.md
      - ArgoCD: projects/argocd.md
      - Terraform:
          - Modules: 
              - AWS VPC: projects/terraform/modules/vpc.md
              - AWS Backend: projects/terraform/modules/backend.md
      - iOS Projects:
          - Overview: projects/ios/overview.md
          - Ludo AR: projects/ios/ludoar.md
          - AR Business Card: projects/ios/arbusinesscard.md

plugins:
  - search
  - mermaid2
  - external-markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - neoteroi.cards
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - neoteroi.timeline
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tapanpatel11
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tapanpatel11
    - icon: fontawesome/solid/envelope
      link: mailto:tapan.patel@dal.ca
extra_css:
  - css/neoteroi-mkdocs.css
footer: >
  Made with ❤️ using [MkDocs Material](https://squidfunk.github.io/mkdocs-material/).  
  Contact me via [GitHub](https://github.com/tapanpatel11),  
  [LinkedIn](https://linkedin.com/in/tapanpatel11), or [Email](mailto:tapan.patel@dal.ca).  

copyright: Copyright &copy; 2024 Tapan Patel